---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        language_version: python3
        additional_dependencies:
          - click==8.0.4
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: git-secrets
        name: git-secrets
        entry: git-secrets --pre_commit_hook --
        language: system
