services:
  website-pylint:
    build:
      context: .
      dockerfile: website/website.dockerfile
      target: development
    command: python -m pylint website/src/website
    volumes:
      - ./website/src/website:/app/website/src/website
      - /app/website/src/website/static
      - /app/website/src/website/templates/frontend
  worker-pylint:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
      target: development
    command: python -m pylint worker/src/worker
    volumes:
      - ./worker/src/worker:/app/worker/src/worker
