services:
  frontend-dev:
    build:
      context: .
      dockerfile: frontend/frontend-dev.dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
  website-dev:
    build:
      context: .
      dockerfile: website/website.dockerfile
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings.development
      - GCP_PROJECT
      - GOOGLE_AUTH_CLIENT_ID
    volumes:
      - ./website/src/website:/app/website/src/website
      - /app/website/src/website/static
      - /app/website/src/website/templates/frontend
      - ./calculator/src/calculator:/app/calculator/src/calculator
  worker-dev:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=worker.settings.development
    volumes:
      - ./worker/src/worker:/app/worker/src/worker
      - ./calculator/src/calculator:/app/calculator/src/calculator
