# Generated by Django 3.2 on 2023-05-14 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calculator", "0002_variantlistannotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicVariantList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="p",
                        max_length=1,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_public_lists",
                        related_query_name="reviewed_public_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_public_lists",
                        related_query_name="submitted_public_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_status",
                        related_query_name="public_status",
                        to="calculator.variantlist",
                    ),
                ),
            ],
        ),
    ]
