# Generated by Django 3.2 on 2023-07-27 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calculator", "0002_variantlistannotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicVariantList",
            fields=[
                (
                    "variant_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="public_status",
                        related_query_name="public_status",
                        serialize=False,
                        to="calculator.variantlist",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Rejected"),
                            ("A", "Approved"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
