# Generated by Django 3.2 on 2023-09-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calculator", "0003_variantlistpublicstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantlistannotation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_list_annotations",
                related_query_name="variant_list_annotation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
