# Generated by Django 3.2 on 2023-09-25 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_variantlistpublicstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantListSharedAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("selected_variants", models.JSONField(default=list)),
                ("variant_notes", models.JSONField(default=dict)),
                (
                    "variant_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_annotations",
                        related_query_name="shared_annotations",
                        to="calculator.variantlist",
                    ),
                ),
            ],
        ),
    ]
