# Generated by Django 3.2 on 2024-01-25 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_alter_variantlistannotation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("label", models.CharField(max_length=1000)),
                ("notes", models.TextField(default="")),
                ("metadata", models.JSONField()),
                ("variants", models.JSONField(default=list)),
                ("top_ten_variants", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Q", "Queued"),
                            ("P", "Processing"),
                            ("R", "Ready"),
                            ("E", "Error"),
                        ],
                        default="Q",
                        max_length=1,
                    ),
                ),
                ("error", models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="dashboardlist",
            index=models.Index(fields=["uuid"], name="calculator__uuid_3c37a2_idx"),
        ),
    ]
