# Generated by Django 3.2 on 2024-03-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_alter_variantlistannotation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_id", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=1000)),
                ("notes", models.TextField(default="")),
                ("created_at", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("total_allele_frequency", models.JSONField(default=list)),
                ("carrier_frequency", models.JSONField(default=list)),
                ("genetic_prevalence", models.JSONField(default=list)),
                (
                    "genetic_prevalence_orphanet",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "genetic_prevalence_genereviews",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "genetic_prevalence_other",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "genetic_incidence_other",
                    models.CharField(blank=True, max_length=100),
                ),
                ("top_ten_variants", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Q", "Queued"),
                            ("P", "Processing"),
                            ("R", "Ready"),
                            ("E", "Error"),
                        ],
                        default="Q",
                        max_length=1,
                    ),
                ),
                ("error", models.TextField(default=None, null=True)),
                (
                    "public_variant_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_variant_list",
                        related_query_name="public_variant_list",
                        to="calculator.variantlist",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dashboardlist",
            index=models.Index(
                fields=["gene_id"], name="calculator__gene_id_6e1ef0_idx"
            ),
        ),
    ]
