# Generated by Django 3.2 on 2024-05-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_variantlistannotation_variant_calculations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="variantlist",
            name="calculator__public__7dc677_idx",
        ),
        migrations.RenameField(
            model_name="variantlist",
            old_name="public_status",
            new_name="representative_status",
        ),
        migrations.RenameField(
            model_name="variantlist",
            old_name="public_status_updated_by",
            new_name="representative_status_updated_by",
        ),
        migrations.RemoveField(
            model_name="dashboardlist",
            name="public_variant_list",
        ),
        migrations.AddField(
            model_name="dashboardlist",
            name="representative_variant_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representative_variant_list",
                related_query_name="representative_variant_list",
                to="calculator.variantlist",
            ),
        ),
        migrations.AddField(
            model_name="variantlist",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="variantlist",
            index=models.Index(
                fields=["representative_status"], name="calculator__represe_2c759e_idx"
            ),
        ),
    ]
