# Generated by Django 3.2 on 2024-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0007_rename_publicstatus_to_representativestatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardlist",
            name="carrier_frequency",
        ),
        migrations.RemoveField(
            model_name="dashboardlist",
            name="genetic_prevalence",
        ),
        migrations.RemoveField(
            model_name="dashboardlist",
            name="total_allele_frequency",
        ),
        migrations.AddField(
            model_name="dashboardlist",
            name="variant_calculations",
            field=models.JSONField(default=dict),
        ),
    ]
