# Generated by Django 3.2 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0008_alter_dashboardlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardlist",
            name="inheritance_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
