# Generated by Django 3.2 on 2024-05-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_dashboardlist_inheritance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantlist",
            name="structural_variants",
            field=models.JSONField(default=list),
        ),
    ]
