# Generated by Django 3.2 on 2024-05-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_variantlist_structural_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantlist",
            name="supporting_document",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
