# Generated by Django 3.2 on 2024-05-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_variantlist_supporting_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantlistannotation",
            name="include_homozygotes_in_calculations",
            field=models.BooleanField(default=True),
        ),
    ]
