# Generated by Django 3.2 on 2024-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0012_variantlistannotation_include_homozygotes_in_calculations",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variantlist",
            name="supporting_document",
        ),
        migrations.AddField(
            model_name="variantlist",
            name="supporting_documents",
            field=models.JSONField(default=list),
        ),
    ]
