# Generated by Django 3.2 on 2024-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calculator",
            "0013_variantlist_support_documents",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variantlistannotation",
            name="not_included_variants",
            field=models.JSONField(default=list),
        ),
    ]
