# Generated by Django 3.2 on 2024-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0014_add_not_included_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantlistannotation",
            name="tagged_groups",
            field=models.JSONField(default=dict),
        ),
    ]
