# Generated by Django 3.2 on 2025-05-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0015_variantlistannotation_tagged_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="DominantDashboardList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_id", models.CharField(max_length=100, unique=True)),
                ("de_novo_variant_calculations", models.JSONField(default=dict)),
                ("date_created", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("inheritance_type", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="dashboardlist",
            name="inheritance_type",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="dominantdashboardlist",
            index=models.Index(
                fields=["gene_id"], name="calculator__gene_id_1c6073_idx"
            ),
        ),
        migrations.AddField(
            model_name="dashboardlist",
            name="dominant_dashboard_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dominant_dashboard_list",
                related_query_name="dominant_dashboard_list",
                to="calculator.dominantdashboardlist",
            ),
        ),
    ]
