steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - dataproc
      - clusters
      - create
      - import-gnomad-$BUILD_ID
      - "--image-version=2.3.17-debian12"
      - >-
        --properties=^|||^spark:spark.task.maxFailures=20|||spark:spark.driver.extraJavaOptions=-Xss4M|||spark:spark.executor.extraJavaOptions=-Xss4M|||spark:spark.speculation=true|||hdfs:dfs.replication=1|||dataproc:dataproc.logging.stackdriver.enable=false|||dataproc:dataproc.monitoring.stackdriver.enable=false|||spark:spark.driver.memory=36g|||yarn:yarn.nodemanager.resource.memory-mb=29184|||yarn:yarn.scheduler.maximum-allocation-mb=14592|||spark:spark.executor.cores=4|||spark:spark.executor.memory=5837m|||spark:spark.executor.memoryOverhead=8755m|||spark:spark.memory.storageFraction=0.2|||spark:spark.executorEnv.HAIL_WORKER_OFF_HEAP_MEMORY_PER_CORE_MB=3648
      - >-
        --initialization-actions=gs://hail-common/hailctl/dataproc/0.2.138/init_notebook.py
      - >-
        --metadata=^|||^WHEEL=gs://hail-common/hailctl/dataproc/0.2.138/hail-0.2.138-py3-none-any.whl|||PKGS=aiodns==2.0.0|aiohappyeyeballs==2.6.1|aiohttp==3.13.5|aiosignal==1.4.0|annotated-doc==0.0.4|async-timeout==5.0.1|attrs==26.1.0|avro==1.11.5|azure-common==1.1.28|azure-core==1.39.0|azure-identity==1.25.3|azure-mgmt-core==1.6.0|azure-mgmt-storage==20.1.0|azure-storage-blob==12.28.0|bokeh==3.4.3|boto3==1.42.84|botocore==1.42.84|certifi==2026.2.25|cffi==2.0.0|charset-normalizer==3.4.7|click==8.3.2|commonmark==0.9.1|contourpy==1.3.2|cryptography==46.0.6|decorator==4.4.2|deprecated==1.2.18|dill==0.4.1|frozenlist==1.8.0|google-auth-oauthlib==0.8.0|google-auth==2.49.1|humanize==4.15.0|idna==3.11|isodate==0.7.2|janus==1.0.0|jinja2==3.1.6|jmespath==1.1.0|jproperties==2.1.2|markupsafe==3.0.3|msal-extensions==1.3.1|msal==1.35.1|msrest==0.7.1|multidict==6.7.1|nest-asyncio==1.6.0|numpy==2.2.6|oauthlib==3.3.1|orjson==3.11.8|packaging==26.0|pandas==2.3.3|parsimonious==0.11.0|pillow==12.2.0|plotly==5.24.1|propcache==0.4.1|py4j==0.10.9.7|pyasn1-modules==0.4.2|pyasn1==0.6.3|pycares==5.0.1|pycparser==3.0|pygments==2.20.0|pyjwt==2.12.1|python-dateutil==2.9.0.post0|python-json-logger==2.0.7|pytz==2026.1.post1|pyyaml==6.0.3|regex==2026.4.4|requests-oauthlib==2.0.0|requests==2.33.1|rich==12.6.0|s3transfer==0.16.0|scipy==1.15.3|setuptools==81.0.0|shellingham==1.5.4|six==1.17.0|sortedcontainers==2.4.0|tabulate==0.10.0|tenacity==9.1.4|tornado==6.5.5|typer==0.24.1|typing-extensions==4.15.0|tzdata==2026.1|urllib3==2.6.3|uvloop==0.21.0|wrapt==1.17.3|xyzservices==2026.3.0|yarl==1.23.0
      - "--master-machine-type=n1-highmem-8"
      - "--master-boot-disk-size=100GB"
      - "--num-master-local-ssds=0"
      - "--num-secondary-workers=0"
      - "--num-worker-local-ssds=0"
      - "--num-workers=32"
      - "--secondary-worker-boot-disk-size=40GB"
      - "--worker-boot-disk-size=40GB"
      - "--worker-machine-type=n1-standard-8"
      - "--initialization-action-timeout=20m"
      - "--region=us-central1"
      - >-
        --subnet=projects/aggregate-frequency-calculator/regions/us-central1/subnetworks/dataproc
      - >-
        --service-account=data-pipeline@aggregate-frequency-calculator.iam.gserviceaccount.com
      - "--no-address"
      - "--tags=dataproc"
      - "--max-idle=5m"
      - "--max-age=3h"
    id: start-cluster
    entrypoint: gcloud
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - dataproc
      - jobs
      - submit
      - pyspark
      - "--cluster=import-gnomad-$BUILD_ID"
      - "--region=us-central1"
      - ./data-pipelines/prepare_gnomad_variants.py
      - "--"
      - "--quiet"
      - "--gnomad-version=4"
      - "--partitions=100000"
      - >-
        gs://aggregate-frequency-calculator-data/gnomAD/gnomAD_v4.1.1_variants.ht
    id: prepare-gnomad-v4-variants
    entrypoint: gcloud
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - dataproc
      - clusters
      - delete
      - "--quiet"
      - import-gnomad-$BUILD_ID
      - "--region=us-central1"
    id: stop-cluster
    entrypoint: gcloud
timeout: 10800s
logsBucket: gs://aggregate-frequency-calculator-build-logs/data-pipelines/import-gnomad-v4
options:
  logging: GCS_ONLY
substitutions:
  _HAIL_VERSION: 0.2.138
