name: Browser CI
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.19.3"
      - name: Install dependencies
        run: cd frontend && npm install --frozen-lockfile --non-interactive --no-progress
      - name: Run ESLint
        run: cd frontend && npm run-script lint:js
      - name: Type check
        run: cd frontend && npm run-script typecheck
      - name: Verify clean build
        run: cd frontend && npm run-script build
      - name: Run Jest tests
        run: cd frontend && npm run-script test:jest
